// <auto-generated />
using System;
using Hieratica.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hieratica.Migrations
{
    [DbContext(typeof(HieraticaDBContext))]
    partial class HieraticaDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hieratica.MODEL.Cliente", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClienteId"));

                    b.Property<string>("BilheteIdentidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DenominacaoSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NIF")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NIS")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClienteId");

                    b.HasIndex("BilheteIdentidade")
                        .IsUnique();

                    b.HasIndex("NIF")
                        .IsUnique();

                    b.HasIndex("NIS")
                        .IsUnique();

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Hieratica.MODEL.Empresa", b =>
                {
                    b.Property<int>("EmpresaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpresaId"));

                    b.Property<string>("DenominacaoSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NIF")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Telelefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("EmpresaId");

                    b.HasIndex("Designacao")
                        .IsUnique();

                    b.HasIndex("NIF")
                        .IsUnique();

                    b.HasIndex("Telelefone")
                        .IsUnique();

                    b.ToTable("Empresa");
                });

            modelBuilder.Entity("Hieratica.MODEL.Factura", b =>
                {
                    b.Property<int>("FacturaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacturaId"));

                    b.Property<int?>("empresa")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<decimal>("montanteDeImposto")
                        .HasColumnType("Decimal(13,2)");

                    b.Property<string>("motivoDeNaoLiquidacaoDoImposto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("venda")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("FacturaId");

                    b.ToTable("Factura");
                });

            modelBuilder.Entity("Hieratica.MODEL.Produto", b =>
                {
                    b.Property<int>("ProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProdutoId"));

                    b.Property<string>("Designacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<decimal>("preco")
                        .HasColumnType("Decimal(13,2)");

                    b.Property<decimal>("taxaDeImposto")
                        .HasColumnType("Decimal(13,2)");

                    b.HasKey("ProdutoId");

                    b.HasIndex("Designacao")
                        .IsUnique();

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("Hieratica.MODEL.Utilizador", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BilheteIdentidade")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telelefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("empresa")
                        .HasColumnType("int");

                    b.Property<int>("estadoConta")
                        .HasColumnType("int");

                    b.Property<int>("perfil")
                        .HasColumnType("int");

                    b.Property<string>("senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("BilheteIdentidade")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Telelefone")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Utilizador");
                });

            modelBuilder.Entity("Hieratica.MODEL.Venda", b =>
                {
                    b.Property<int>("VendaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VendaId"));

                    b.Property<int>("QuantidadeVendida")
                        .HasColumnType("int");

                    b.Property<int?>("cliente")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateOnly>("dataVenda")
                        .HasColumnType("date");

                    b.Property<int>("produto")
                        .HasColumnType("int");

                    b.Property<decimal>("totalAPagar")
                        .HasColumnType("Decimal(13,2)");

                    b.Property<decimal>("troco")
                        .HasColumnType("Decimal(13,2)");

                    b.Property<decimal>("valorPago")
                        .HasColumnType("decimal(13,2)");

                    b.HasKey("VendaId");

                    b.ToTable("Venda");
                });
#pragma warning restore 612, 618
        }
    }
}
